name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'angular.json'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'angular.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint (if configured)
        run: |
          if npm run | grep -q 'lint'; then npm run lint --if-present; else echo 'No lint script'; fi

      - name: Build production
        run: npx ng build --configuration production

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/**
          retention-days: 5

      - name: Summary
        run: |
          echo "### Frontend Build" >> $GITHUB_STEP_SUMMARY
          echo "Built at $(date -u)" >> $GITHUB_STEP_SUMMARY
