name: Frontend Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or commit) to deploy'
        required: false
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build production
        run: npx ng build --configuration production

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Sync dist to server
        run: |
          rsync -az --delete dist/care-ride-frontend/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/care-ride-frontend/
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "sudo systemctl reload nginx || sudo nginx -s reload || true"

      - name: Smoke Check Root
        run: |
          STATUS=$(curl -fsS -o /dev/null -w '%{http_code}' https://${{ secrets.DOMAIN }}/ || true)
          echo "HTTP Status: $STATUS"; test "$STATUS" = "200"

      - name: Summary
        if: always()
        run: |
          echo "### Frontend Deploy" >> $GITHUB_STEP_SUMMARY
          echo "Ref: ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY
