name: Frontend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'angular.json'
      - 'src/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or commit) to deploy'
        required: false
        default: 'main'

concurrency:
  group: frontend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || 'main' }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build production
        run: npx ng build --configuration production

      - name: Wait for backend health (max ~2 min)
        run: |
          for i in {1..30}; do
            STATUS=$(curl -fsS -o /dev/null -w '%{http_code}' https://${{ secrets.DOMAIN }}/api/actuator/health || true)
            if [ "$STATUS" = "200" ]; then echo "Backend healthy over HTTPS"; break; fi
            STATUS=$(curl -fsS -o /dev/null -w '%{http_code}' http://${{ secrets.DOMAIN }}/api/actuator/health || true)
            if [ "$STATUS" = "200" ]; then echo "Backend healthy over HTTP"; break; fi
            echo "Attempt $i: backend not healthy yet (status=$STATUS)"; sleep 4;
            if [ "$i" = "30" ]; then echo "Backend did not become healthy in time"; exit 1; fi
          done

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Sync dist to server
        run: |
          rsync -az --delete dist/care-ride-frontend/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/care-ride-frontend/
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "sudo systemctl reload nginx || sudo nginx -s reload || true"

      - name: Smoke Check Root
        run: |
          STATUS=$(curl -fsS -o /dev/null -w '%{http_code}' https://${{ secrets.DOMAIN }}/ || true)
          echo "HTTP Status: $STATUS"; test "$STATUS" = "200"

      - name: Summary
        if: always()
        run: |
          echo "### Frontend Deploy" >> $GITHUB_STEP_SUMMARY
          echo "Ref: ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY
